/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.arps.Grimeron.UI;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JTabbedPane;
import org.arps.Grimeron.Grimeron;
import org.arps.Grimeron.Move;
import org.arps.Grimeron.console.Console;
import org.arps.Grimeron.entity.Player;
import org.arps.Grimeron.utils.StatisticSet;

/**
 *
 * @author richa_000
 */
public class GrimeronFrame extends javax.swing.JFrame {

    private GrimeronPanel preconfiguredGamePanel;
    private GrimeronGrid grid;
    private GrimeronStatisticPanel preconfiguredStatPanel; 
    private StatisticSet stats;
    private Grimeron game;
    private Console console;
    
    private DefaultListModel playerListModel = new DefaultListModel();
    private DefaultListModel moveListModel = new DefaultListModel();
    
    private volatile boolean restart = false;
    private volatile boolean waitingForRestart = true;
    /**
     * Creates new form GrimeronFrame
     * @param game
     */
    public GrimeronFrame(Grimeron game, Console console) {
        this.game = game;
        this.console = console;
        initPreComponents();
        initComponents();
        updateConsole();
    }
    
    public void initialize(){
        
    }
    
    public void toggleResetText(boolean toggle){
        this.clickableNo.setVisible(toggle);
        this.clickableYes.setVisible(toggle);
        this.text_restart.setVisible(toggle);
    }
    
    public JTabbedPane getTabbedPane(){
        return this.mainTabbedPanel;
    }

    public GrimeronGrid getGrid() {
        return grid;
    }

    public void setGrid(GrimeronGrid grid) {
        this.grid = grid;
    }

    public StatisticSet getStats() {
        return stats;
    }

    public void setStats(StatisticSet stats) {
        this.stats = stats;
    }
    
    public GrimeronPanel getGamePanel(){
        return this.grimeronPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        mainTabbedPanel = new javax.swing.JTabbedPane();
        activeGamePAnel = new javax.swing.JPanel();
        grimeronPanel = preconfiguredGamePanel;
        statisticPanel = new javax.swing.JPanel();
        gameStats = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        playerInfoPane = new javax.swing.JTabbedPane();
        selectAPlayerPanel = new javax.swing.JPanel();
        text_selectPlayer = new javax.swing.JLabel();
        playerSelectorScrollPane = new javax.swing.JScrollPane();
        playerSelector = new javax.swing.JList(playerListModel);
        text_playerWC = new javax.swing.JLabel();
        playerWinCount = new javax.swing.JLabel();
        text_averagePlace = new javax.swing.JLabel();
        averagePlace = new javax.swing.JLabel();
        playerMoveInfoPanel = new javax.swing.JPanel();
        moveStatScrollPane = new javax.swing.JScrollPane();
        playerMoveSelector = new javax.swing.JList(moveListModel);
        moveInfoText = new javax.swing.JLabel();
        text_avgLifespan = new javax.swing.JLabel();
        averageLifspan = new javax.swing.JLabel();
        overallPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        text_restart = new javax.swing.JLabel();
        clickableYes = new javax.swing.JLabel();
        clickableNo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        consoleOutputField = new javax.swing.JEditorPane();
        consoleInputField = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(18, 31, 57));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        mainTabbedPanel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout activeGamePAnelLayout = new javax.swing.GroupLayout(activeGamePAnel);
        activeGamePAnel.setLayout(activeGamePAnelLayout);
        activeGamePAnelLayout.setHorizontalGroup(
            activeGamePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activeGamePAnelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grimeronPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        activeGamePAnelLayout.setVerticalGroup(
            activeGamePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activeGamePAnelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grimeronPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabbedPanel.addTab("Active Game", activeGamePAnel);

        gameStats.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gameStatsStateChanged(evt);
            }
        });

        text_selectPlayer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_selectPlayer.setText("Select a player!");

        playerSelector.setBackground(new java.awt.Color(204, 204, 204));
        playerSelector.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                playerSelectorValueChanged(evt);
            }
        });
        playerSelectorScrollPane.setViewportView(playerSelector);

        text_playerWC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        text_playerWC.setText("Player Win Count:");

        playerWinCount.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        playerWinCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerWinCount.setText("0");

        text_averagePlace.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        text_averagePlace.setText("Average Place");

        averagePlace.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        averagePlace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        averagePlace.setText("0");

        playerMoveInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Player Move Stats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        playerMoveSelector.setBackground(new java.awt.Color(204, 204, 204));
        moveStatScrollPane.setViewportView(playerMoveSelector);

        moveInfoText.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        moveInfoText.setText("Move Information: ");
        moveInfoText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout playerMoveInfoPanelLayout = new javax.swing.GroupLayout(playerMoveInfoPanel);
        playerMoveInfoPanel.setLayout(playerMoveInfoPanelLayout);
        playerMoveInfoPanelLayout.setHorizontalGroup(
            playerMoveInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerMoveInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerMoveInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moveInfoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moveStatScrollPane))
                .addContainerGap())
        );
        playerMoveInfoPanelLayout.setVerticalGroup(
            playerMoveInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerMoveInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveStatScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moveInfoText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        text_avgLifespan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        text_avgLifespan.setText("Average Lifespan");

        averageLifspan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        averageLifspan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        averageLifspan.setText("0");

        javax.swing.GroupLayout selectAPlayerPanelLayout = new javax.swing.GroupLayout(selectAPlayerPanel);
        selectAPlayerPanel.setLayout(selectAPlayerPanelLayout);
        selectAPlayerPanelLayout.setHorizontalGroup(
            selectAPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectAPlayerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectAPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerSelectorScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, selectAPlayerPanelLayout.createSequentialGroup()
                        .addComponent(text_selectPlayer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, selectAPlayerPanelLayout.createSequentialGroup()
                        .addComponent(text_playerWC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerWinCount, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_averagePlace, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(averagePlace, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_avgLifespan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(averageLifspan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(playerMoveInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        selectAPlayerPanelLayout.setVerticalGroup(
            selectAPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectAPlayerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_selectPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerSelectorScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectAPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_playerWC)
                    .addComponent(playerWinCount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_averagePlace)
                    .addComponent(averagePlace)
                    .addComponent(text_avgLifespan)
                    .addComponent(averageLifspan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerMoveInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        playerInfoPane.addTab("Player Info", selectAPlayerPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerInfoPane)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerInfoPane)
                .addContainerGap())
        );

        gameStats.addTab("Game Stats", jPanel2);

        javax.swing.GroupLayout overallPanelLayout = new javax.swing.GroupLayout(overallPanel);
        overallPanel.setLayout(overallPanelLayout);
        overallPanelLayout.setHorizontalGroup(
            overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        overallPanelLayout.setVerticalGroup(
            overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        gameStats.addTab("Overall Stats", overallPanel);

        javax.swing.GroupLayout statisticPanelLayout = new javax.swing.GroupLayout(statisticPanel);
        statisticPanel.setLayout(statisticPanelLayout);
        statisticPanelLayout.setHorizontalGroup(
            statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameStats)
        );
        statisticPanelLayout.setVerticalGroup(
            statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameStats)
        );

        mainTabbedPanel.addTab("Statistic Panel", statisticPanel);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grimeron");

        text_restart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text_restart.setText("Restart Game?");
        text_restart.setVisible(false);

        clickableYes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clickableYes.setForeground(new java.awt.Color(51, 51, 51));
        clickableYes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clickableYes.setText("Yes");
        clickableYes.setVisible(false);
        clickableYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clickableYesMousePressed(evt);
            }
        });

        clickableNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clickableNo.setForeground(new java.awt.Color(51, 51, 51));
        clickableNo.setText("No");
        clickableNo.setVisible(false);
        clickableNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clickableNoMousePressed(evt);
            }
        });

        consoleOutputField.setEditable(false);
        consoleOutputField.setBackground(new java.awt.Color(232, 232, 255));
        consoleOutputField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        consoleOutputField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        consoleOutputField.setSelectionColor(new java.awt.Color(204, 255, 204));
        jScrollPane2.setViewportView(consoleOutputField);

        consoleInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                consoleInputFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(text_restart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(clickableYes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(clickableNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(256, 256, 256))
            .addGroup(layout.createSequentialGroup()
                .addGap(631, 631, 631)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consoleInputField)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.CENTER))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_restart)
                    .addComponent(clickableYes)
                    .addComponent(clickableNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consoleInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(mainTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initPreComponents(){
        grid = new GrimeronGrid();
        stats = new StatisticSet(game);
        preconfiguredGamePanel = new GrimeronPanel(grid);
        preconfiguredStatPanel = new GrimeronStatisticPanel(stats);
    }
    
    private void clickableYesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickableYesMousePressed
        game.resetGame();
        restart = true;
        waitingForRestart = false;
        try {
            Thread.sleep(5);
        } catch (InterruptedException ex) {
        }
    }//GEN-LAST:event_clickableYesMousePressed

    private void clickableNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickableNoMousePressed
        waitingForRestart = false;
        this.dispose();
    }//GEN-LAST:event_clickableNoMousePressed

    private void consoleInputFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consoleInputFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            console.attemptCommand(consoleInputField.getText());
            consoleInputField.setText("");
        }
        
        consoleOutputField.setText(console.getOutput());
    }//GEN-LAST:event_consoleInputFieldKeyPressed

    private void playerSelectorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_playerSelectorValueChanged
        try
        {
            Player selectedPlayer = (Player)playerSelector.getSelectedValue();
            
            moveListModel.removeAllElements();
            
            for(Move move: selectedPlayer.getMoveHistory())
            {
                moveListModel.addElement(move);
            }
        } catch(ClassCastException ex) {
            
        } catch(NullPointerException ex) {
            
        }
        
        this.repaint();
        System.out.println("Player selection event occured.");
    }//GEN-LAST:event_playerSelectorValueChanged

    private void gameStatsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gameStatsStateChanged
        updateStatistics(game);
    }//GEN-LAST:event_gameStatsStateChanged

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        repaint();
    }//GEN-LAST:event_formMouseEntered

    
    private void updateGameStats()
    {
        playerListModel.removeAllElements();
        
        for(Player player: game.getRuleSet().getPlayers())
        {
            playerListModel.addElement(player);
        } 
        repaint();
    }
    
    private void updateOverallStats()
    {
        
    }
    
    public void updateConsole(){
        consoleOutputField.setText(console.getOutput());
    }
    
    public boolean getRestart(){
        return restart;
    }
    
    public void setRestart(boolean restart){
        this.restart = restart;
    }

    public boolean isWaitingForRestart() {
        return waitingForRestart;
    }

    public void setWaitingForRestart(boolean waitingForRestart) {
        this.waitingForRestart = waitingForRestart;
    }
    
    public void updateStatistics(Grimeron game){
        stats.updateStatistics(game);
        updateGameStats();
        updateOverallStats();
        repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activeGamePAnel;
    private javax.swing.JLabel averageLifspan;
    private javax.swing.JLabel averagePlace;
    public javax.swing.JLabel clickableNo;
    public javax.swing.JLabel clickableYes;
    private javax.swing.JFormattedTextField consoleInputField;
    private javax.swing.JEditorPane consoleOutputField;
    private javax.swing.JTabbedPane gameStats;
    private org.arps.Grimeron.UI.GrimeronPanel grimeronPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane mainTabbedPanel;
    private javax.swing.JLabel moveInfoText;
    private javax.swing.JScrollPane moveStatScrollPane;
    private javax.swing.JPanel overallPanel;
    private javax.swing.JTabbedPane playerInfoPane;
    private javax.swing.JPanel playerMoveInfoPanel;
    private javax.swing.JList playerMoveSelector;
    private javax.swing.JList playerSelector;
    private javax.swing.JScrollPane playerSelectorScrollPane;
    private javax.swing.JLabel playerWinCount;
    private javax.swing.JPanel selectAPlayerPanel;
    private javax.swing.JPanel statisticPanel;
    private javax.swing.JLabel text_averagePlace;
    private javax.swing.JLabel text_avgLifespan;
    private javax.swing.JLabel text_playerWC;
    public javax.swing.JLabel text_restart;
    private javax.swing.JLabel text_selectPlayer;
    // End of variables declaration//GEN-END:variables

}
